baseURL = "https://glumes.com/"
languageCode = "zh-cn"
DefaultContentLanguage = "en"
title = "纸上浅谈"
theme = "beautifulhugo_bak"

pygmentsUseClasses = false
pygmentCodeFences = true

metaDataFormat = "yaml"

hasCJKLanguage = true

latexDashes = true

disqusShortname = "glumes"

googleAnalytics = "UA-84590324-2"

[Params]
     hello = "纸上浅谈"
     subtitle = "多媒体开发札记"
	 useChroma = true
	 commit = false
	 rss = true
	 comments = true
     addReward = true
     original = true
     addwechat = true
     addplanet = true
       reward = true



[[Params.bigimg]]
src = "https://ae01.alicdn.com/kf/U8e416f129f5040ec903a219b08d4ffcdl.jpg"
desc = "广州 · 老城区"


[[Params.bigimg]]
src = "https://ae01.alicdn.com/kf/U18dc68030de44ec1939bd785e5049c284.jpg"
desc = "凤凰古城"



[Author]
	name = "Glumes"
	website = "http://www.glumes.com"
	email = "zhaoying9402@gmail.com"
	github = "glumes"

[[menu.main]]
    identifier = "Categories"
    name = "目录"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "Android"
    url = "categories/android"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "opencv"
    url = "categories/opencv"
    weight = 2


[[menu.main]]
    parent = "Categories"
    name = "opengl"
    url = "categories/opengl"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "ffmpeg"
    url = "categories/音视频开发"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "python"
    url = "categories/python"
    weight = 5


[[menu.main]]
    name = "生活"
    url = "categories/life"
    weight = 2

[[menu.main]]
	identifier = "Tags"
	name = "标签"
	weight = 3
	url = "tags"


[[menu.main]]
    identifier = "about"
	name = "关于"
	url = "about/"
	weight = 4

[[menu.main]]
    identifier = "post"
    name = "文章集"
    url = "post/"
    weight = 5





